### ISSUE TITLE
PasswordEditText问题

### ISSUE THREAD

**Issue by Fisherman91** [tyzlmjj/AndroidUI#2]
看了您的代码，感觉写的非常不错，只是用PasswordEditText的时候发现一个问题：只要我用android.support.design.widget.TextInputLayout包住就会显示系统默认的小眼睛图标（这样就总共有三个图标了），单独使用PasswordEditText就没问题

**Comment by tyzlmjj** [comment]
TextInputLayout 有自定义属性，可以去掉它的小眼睛图标！

**Comment by Fisherman91** [comment]
谢谢，已解决
